//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryStreamCloudWinServ.Customer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShipmentRequest", Namespace="http://schemas.datacontract.org/2004/07/DeliveryStreamCustomerWCF.Entities")]
    [System.SerializableAttribute()]
    public partial class ShipmentRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte>[] BOLImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DeliveryStreamCloudWinServ.Customer.ShipmentRequestComponents[] ComponentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExtSysTrxLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderLoadReviewEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplyPointCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SysTrxLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SysTrxNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrailerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte>[] BOLImage {
            get {
                return this.BOLImageField;
            }
            set {
                if ((object.ReferenceEquals(this.BOLImageField, value) != true)) {
                    this.BOLImageField = value;
                    this.RaisePropertyChanged("BOLImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DeliveryStreamCloudWinServ.Customer.ShipmentRequestComponents[] Components {
            get {
                return this.ComponentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ComponentsField, value) != true)) {
                    this.ComponentsField = value;
                    this.RaisePropertyChanged("Components");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExtSysTrxLine {
            get {
                return this.ExtSysTrxLineField;
            }
            set {
                if ((this.ExtSysTrxLineField.Equals(value) != true)) {
                    this.ExtSysTrxLineField = value;
                    this.RaisePropertyChanged("ExtSysTrxLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderLoadReviewEnabled {
            get {
                return this.OrderLoadReviewEnabledField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderLoadReviewEnabledField, value) != true)) {
                    this.OrderLoadReviewEnabledField = value;
                    this.RaisePropertyChanged("OrderLoadReviewEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierCode {
            get {
                return this.SupplierCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierCodeField, value) != true)) {
                    this.SupplierCodeField = value;
                    this.RaisePropertyChanged("SupplierCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplyPointCode {
            get {
                return this.SupplyPointCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplyPointCodeField, value) != true)) {
                    this.SupplyPointCodeField = value;
                    this.RaisePropertyChanged("SupplyPointCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SysTrxLine {
            get {
                return this.SysTrxLineField;
            }
            set {
                if ((this.SysTrxLineField.Equals(value) != true)) {
                    this.SysTrxLineField = value;
                    this.RaisePropertyChanged("SysTrxLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SysTrxNo {
            get {
                return this.SysTrxNoField;
            }
            set {
                if ((this.SysTrxNoField.Equals(value) != true)) {
                    this.SysTrxNoField = value;
                    this.RaisePropertyChanged("SysTrxNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrailerCode {
            get {
                return this.TrailerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TrailerCodeField, value) != true)) {
                    this.TrailerCodeField = value;
                    this.RaisePropertyChanged("TrailerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShipmentRequestComponents", Namespace="http://schemas.datacontract.org/2004/07/DeliveryStreamCustomerWCF.Entities")]
    [System.SerializableAttribute()]
    public partial class ShipmentRequestComponents : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BOLDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BOLEndDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BOLImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BOLNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BOLQtyVarianceReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ComponentNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExtSysTrxLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GrossQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NetQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplyPointCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrailerCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BOLDateTime {
            get {
                return this.BOLDateTimeField;
            }
            set {
                if ((this.BOLDateTimeField.Equals(value) != true)) {
                    this.BOLDateTimeField = value;
                    this.RaisePropertyChanged("BOLDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BOLEndDateTime {
            get {
                return this.BOLEndDateTimeField;
            }
            set {
                if ((this.BOLEndDateTimeField.Equals(value) != true)) {
                    this.BOLEndDateTimeField = value;
                    this.RaisePropertyChanged("BOLEndDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] BOLImage {
            get {
                return this.BOLImageField;
            }
            set {
                if ((object.ReferenceEquals(this.BOLImageField, value) != true)) {
                    this.BOLImageField = value;
                    this.RaisePropertyChanged("BOLImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BOLNo {
            get {
                return this.BOLNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BOLNoField, value) != true)) {
                    this.BOLNoField = value;
                    this.RaisePropertyChanged("BOLNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BOLQtyVarianceReason {
            get {
                return this.BOLQtyVarianceReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.BOLQtyVarianceReasonField, value) != true)) {
                    this.BOLQtyVarianceReasonField = value;
                    this.RaisePropertyChanged("BOLQtyVarianceReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ComponentNo {
            get {
                return this.ComponentNoField;
            }
            set {
                if ((this.ComponentNoField.Equals(value) != true)) {
                    this.ComponentNoField = value;
                    this.RaisePropertyChanged("ComponentNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExtSysTrxLine {
            get {
                return this.ExtSysTrxLineField;
            }
            set {
                if ((this.ExtSysTrxLineField.Equals(value) != true)) {
                    this.ExtSysTrxLineField = value;
                    this.RaisePropertyChanged("ExtSysTrxLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GrossQty {
            get {
                return this.GrossQtyField;
            }
            set {
                if ((this.GrossQtyField.Equals(value) != true)) {
                    this.GrossQtyField = value;
                    this.RaisePropertyChanged("GrossQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NetQty {
            get {
                return this.NetQtyField;
            }
            set {
                if ((this.NetQtyField.Equals(value) != true)) {
                    this.NetQtyField = value;
                    this.RaisePropertyChanged("NetQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierCode {
            get {
                return this.SupplierCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierCodeField, value) != true)) {
                    this.SupplierCodeField = value;
                    this.RaisePropertyChanged("SupplierCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplyPointCode {
            get {
                return this.SupplyPointCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplyPointCodeField, value) != true)) {
                    this.SupplyPointCodeField = value;
                    this.RaisePropertyChanged("SupplyPointCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrailerCode {
            get {
                return this.TrailerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TrailerCodeField, value) != true)) {
                    this.TrailerCodeField = value;
                    this.RaisePropertyChanged("TrailerCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShipmentResponse", Namespace="http://schemas.datacontract.org/2004/07/DeliveryStreamCustomerWCF.Entities")]
    [System.SerializableAttribute()]
    public partial class ShipmentResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OrderLoadReviewEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShipDocSysTrxLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ShipDocSysTrxNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OrderLoadReviewEnabled {
            get {
                return this.OrderLoadReviewEnabledField;
            }
            set {
                if ((this.OrderLoadReviewEnabledField.Equals(value) != true)) {
                    this.OrderLoadReviewEnabledField = value;
                    this.RaisePropertyChanged("OrderLoadReviewEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShipDocSysTrxLine {
            get {
                return this.ShipDocSysTrxLineField;
            }
            set {
                if ((this.ShipDocSysTrxLineField.Equals(value) != true)) {
                    this.ShipDocSysTrxLineField = value;
                    this.RaisePropertyChanged("ShipDocSysTrxLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ShipDocSysTrxNo {
            get {
                return this.ShipDocSysTrxNoField;
            }
            set {
                if ((this.ShipDocSysTrxNoField.Equals(value) != true)) {
                    this.ShipDocSysTrxNoField = value;
                    this.RaisePropertyChanged("ShipDocSysTrxNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryRequest", Namespace="http://schemas.datacontract.org/2004/07/DeliveryStreamCustomerWCF.Entities")]
    [System.SerializableAttribute()]
    public partial class DeliveryRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BOLWaitTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BOLWaitTimeTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DiversionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Diversion_CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DeliveryStreamCloudWinServ.Customer.DeliveryRequestItems[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MinimumLoadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MinimumLoad_CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderLoadReviewEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OtherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Other_CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PumpOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PumpOut_CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SignatureDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] SignatureImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignatureStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SiteWaitTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteWaitTime_CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SiteWaitTime_EndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SiteWaitTime_StartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SplitDropField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SplitDrop_CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SplitLoadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SplitLoad_CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SysTrxNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BOLWaitTime {
            get {
                return this.BOLWaitTimeField;
            }
            set {
                if ((this.BOLWaitTimeField.Equals(value) != true)) {
                    this.BOLWaitTimeField = value;
                    this.RaisePropertyChanged("BOLWaitTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BOLWaitTimeTotal {
            get {
                return this.BOLWaitTimeTotalField;
            }
            set {
                if ((this.BOLWaitTimeTotalField.Equals(value) != true)) {
                    this.BOLWaitTimeTotalField = value;
                    this.RaisePropertyChanged("BOLWaitTimeTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Diversion {
            get {
                return this.DiversionField;
            }
            set {
                if ((this.DiversionField.Equals(value) != true)) {
                    this.DiversionField = value;
                    this.RaisePropertyChanged("Diversion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Diversion_Comment {
            get {
                return this.Diversion_CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.Diversion_CommentField, value) != true)) {
                    this.Diversion_CommentField = value;
                    this.RaisePropertyChanged("Diversion_Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DeliveryStreamCloudWinServ.Customer.DeliveryRequestItems[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MinimumLoad {
            get {
                return this.MinimumLoadField;
            }
            set {
                if ((this.MinimumLoadField.Equals(value) != true)) {
                    this.MinimumLoadField = value;
                    this.RaisePropertyChanged("MinimumLoad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MinimumLoad_Comment {
            get {
                return this.MinimumLoad_CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.MinimumLoad_CommentField, value) != true)) {
                    this.MinimumLoad_CommentField = value;
                    this.RaisePropertyChanged("MinimumLoad_Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderLoadReviewEnabled {
            get {
                return this.OrderLoadReviewEnabledField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderLoadReviewEnabledField, value) != true)) {
                    this.OrderLoadReviewEnabledField = value;
                    this.RaisePropertyChanged("OrderLoadReviewEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Other {
            get {
                return this.OtherField;
            }
            set {
                if ((this.OtherField.Equals(value) != true)) {
                    this.OtherField = value;
                    this.RaisePropertyChanged("Other");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Other_Comment {
            get {
                return this.Other_CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.Other_CommentField, value) != true)) {
                    this.Other_CommentField = value;
                    this.RaisePropertyChanged("Other_Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PumpOut {
            get {
                return this.PumpOutField;
            }
            set {
                if ((this.PumpOutField.Equals(value) != true)) {
                    this.PumpOutField = value;
                    this.RaisePropertyChanged("PumpOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PumpOut_Comment {
            get {
                return this.PumpOut_CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.PumpOut_CommentField, value) != true)) {
                    this.PumpOut_CommentField = value;
                    this.RaisePropertyChanged("PumpOut_Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SignatureDateTime {
            get {
                return this.SignatureDateTimeField;
            }
            set {
                if ((this.SignatureDateTimeField.Equals(value) != true)) {
                    this.SignatureDateTimeField = value;
                    this.RaisePropertyChanged("SignatureDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] SignatureImage {
            get {
                return this.SignatureImageField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureImageField, value) != true)) {
                    this.SignatureImageField = value;
                    this.RaisePropertyChanged("SignatureImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignatureStatus {
            get {
                return this.SignatureStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureStatusField, value) != true)) {
                    this.SignatureStatusField = value;
                    this.RaisePropertyChanged("SignatureStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SiteWaitTime {
            get {
                return this.SiteWaitTimeField;
            }
            set {
                if ((this.SiteWaitTimeField.Equals(value) != true)) {
                    this.SiteWaitTimeField = value;
                    this.RaisePropertyChanged("SiteWaitTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteWaitTime_Comment {
            get {
                return this.SiteWaitTime_CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteWaitTime_CommentField, value) != true)) {
                    this.SiteWaitTime_CommentField = value;
                    this.RaisePropertyChanged("SiteWaitTime_Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SiteWaitTime_End {
            get {
                return this.SiteWaitTime_EndField;
            }
            set {
                if ((this.SiteWaitTime_EndField.Equals(value) != true)) {
                    this.SiteWaitTime_EndField = value;
                    this.RaisePropertyChanged("SiteWaitTime_End");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SiteWaitTime_Start {
            get {
                return this.SiteWaitTime_StartField;
            }
            set {
                if ((this.SiteWaitTime_StartField.Equals(value) != true)) {
                    this.SiteWaitTime_StartField = value;
                    this.RaisePropertyChanged("SiteWaitTime_Start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SplitDrop {
            get {
                return this.SplitDropField;
            }
            set {
                if ((this.SplitDropField.Equals(value) != true)) {
                    this.SplitDropField = value;
                    this.RaisePropertyChanged("SplitDrop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SplitDrop_Comment {
            get {
                return this.SplitDrop_CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.SplitDrop_CommentField, value) != true)) {
                    this.SplitDrop_CommentField = value;
                    this.RaisePropertyChanged("SplitDrop_Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SplitLoad {
            get {
                return this.SplitLoadField;
            }
            set {
                if ((this.SplitLoadField.Equals(value) != true)) {
                    this.SplitLoadField = value;
                    this.RaisePropertyChanged("SplitLoad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SplitLoad_Comment {
            get {
                return this.SplitLoad_CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.SplitLoad_CommentField, value) != true)) {
                    this.SplitLoad_CommentField = value;
                    this.RaisePropertyChanged("SplitLoad_Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SysTrxNo {
            get {
                return this.SysTrxNoField;
            }
            set {
                if ((this.SysTrxNoField.Equals(value) != true)) {
                    this.SysTrxNoField = value;
                    this.RaisePropertyChanged("SysTrxNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryRequestItems", Namespace="http://schemas.datacontract.org/2004/07/DeliveryStreamCustomerWCF.Entities")]
    [System.SerializableAttribute()]
    public partial class DeliveryRequestItems : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AfterVolumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BOLNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BeforeVolumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DelivDtTmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DeliveryImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DeliveryImagePdfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryQtyVarianceReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GrossQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NetQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OrderItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShipDocSysTrxLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ShipDocSysTrxNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SysLineNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AfterVolume {
            get {
                return this.AfterVolumeField;
            }
            set {
                if ((this.AfterVolumeField.Equals(value) != true)) {
                    this.AfterVolumeField = value;
                    this.RaisePropertyChanged("AfterVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BOLNo {
            get {
                return this.BOLNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BOLNoField, value) != true)) {
                    this.BOLNoField = value;
                    this.RaisePropertyChanged("BOLNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BeforeVolume {
            get {
                return this.BeforeVolumeField;
            }
            set {
                if ((this.BeforeVolumeField.Equals(value) != true)) {
                    this.BeforeVolumeField = value;
                    this.RaisePropertyChanged("BeforeVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DelivDtTm {
            get {
                return this.DelivDtTmField;
            }
            set {
                if ((this.DelivDtTmField.Equals(value) != true)) {
                    this.DelivDtTmField = value;
                    this.RaisePropertyChanged("DelivDtTm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DeliveryImage {
            get {
                return this.DeliveryImageField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryImageField, value) != true)) {
                    this.DeliveryImageField = value;
                    this.RaisePropertyChanged("DeliveryImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DeliveryImagePdf {
            get {
                return this.DeliveryImagePdfField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryImagePdfField, value) != true)) {
                    this.DeliveryImagePdfField = value;
                    this.RaisePropertyChanged("DeliveryImagePdf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryQtyVarianceReason {
            get {
                return this.DeliveryQtyVarianceReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryQtyVarianceReasonField, value) != true)) {
                    this.DeliveryQtyVarianceReasonField = value;
                    this.RaisePropertyChanged("DeliveryQtyVarianceReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GrossQty {
            get {
                return this.GrossQtyField;
            }
            set {
                if ((this.GrossQtyField.Equals(value) != true)) {
                    this.GrossQtyField = value;
                    this.RaisePropertyChanged("GrossQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NetQty {
            get {
                return this.NetQtyField;
            }
            set {
                if ((this.NetQtyField.Equals(value) != true)) {
                    this.NetQtyField = value;
                    this.RaisePropertyChanged("NetQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OrderItemID {
            get {
                return this.OrderItemIDField;
            }
            set {
                if ((this.OrderItemIDField.Equals(value) != true)) {
                    this.OrderItemIDField = value;
                    this.RaisePropertyChanged("OrderItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShipDocSysTrxLine {
            get {
                return this.ShipDocSysTrxLineField;
            }
            set {
                if ((this.ShipDocSysTrxLineField.Equals(value) != true)) {
                    this.ShipDocSysTrxLineField = value;
                    this.RaisePropertyChanged("ShipDocSysTrxLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ShipDocSysTrxNo {
            get {
                return this.ShipDocSysTrxNoField;
            }
            set {
                if ((this.ShipDocSysTrxNoField.Equals(value) != true)) {
                    this.ShipDocSysTrxNoField = value;
                    this.RaisePropertyChanged("ShipDocSysTrxNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SysLineNo {
            get {
                return this.SysLineNoField;
            }
            set {
                if ((this.SysLineNoField.Equals(value) != true)) {
                    this.SysLineNoField = value;
                    this.RaisePropertyChanged("SysLineNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TWBOLDetails", Namespace="http://schemas.datacontract.org/2004/07/DeliveryStreamCustomerWCF.Entities")]
    [System.SerializableAttribute()]
    public partial class TWBOLDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BOLDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid BOLHdrIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DeliveryStreamCloudWinServ.Customer.TWBOLItemDetails[] BOLItemDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BOLNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplyPointCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UpdatedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BOLDateTime {
            get {
                return this.BOLDateTimeField;
            }
            set {
                if ((this.BOLDateTimeField.Equals(value) != true)) {
                    this.BOLDateTimeField = value;
                    this.RaisePropertyChanged("BOLDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid BOLHdrID {
            get {
                return this.BOLHdrIDField;
            }
            set {
                if ((this.BOLHdrIDField.Equals(value) != true)) {
                    this.BOLHdrIDField = value;
                    this.RaisePropertyChanged("BOLHdrID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DeliveryStreamCloudWinServ.Customer.TWBOLItemDetails[] BOLItemDetails {
            get {
                return this.BOLItemDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.BOLItemDetailsField, value) != true)) {
                    this.BOLItemDetailsField = value;
                    this.RaisePropertyChanged("BOLItemDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BOLNo {
            get {
                return this.BOLNoField;
            }
            set {
                if ((object.ReferenceEquals(this.BOLNoField, value) != true)) {
                    this.BOLNoField = value;
                    this.RaisePropertyChanged("BOLNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((this.ClientIDField.Equals(value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierCode {
            get {
                return this.SupplierCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierCodeField, value) != true)) {
                    this.SupplierCodeField = value;
                    this.RaisePropertyChanged("SupplierCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplyPointCode {
            get {
                return this.SupplyPointCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplyPointCodeField, value) != true)) {
                    this.SupplyPointCodeField = value;
                    this.RaisePropertyChanged("SupplyPointCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UpdatedBy {
            get {
                return this.UpdatedByField;
            }
            set {
                if ((this.UpdatedByField.Equals(value) != true)) {
                    this.UpdatedByField = value;
                    this.RaisePropertyChanged("UpdatedBy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TWBOLItemDetails", Namespace="http://schemas.datacontract.org/2004/07/DeliveryStreamCustomerWCF.Entities")]
    [System.SerializableAttribute()]
    public partial class TWBOLItemDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompartmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GrossQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NetQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OrderedQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SystrxLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SystrxNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompartmentID {
            get {
                return this.CompartmentIDField;
            }
            set {
                if ((this.CompartmentIDField.Equals(value) != true)) {
                    this.CompartmentIDField = value;
                    this.RaisePropertyChanged("CompartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GrossQty {
            get {
                return this.GrossQtyField;
            }
            set {
                if ((this.GrossQtyField.Equals(value) != true)) {
                    this.GrossQtyField = value;
                    this.RaisePropertyChanged("GrossQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NetQty {
            get {
                return this.NetQtyField;
            }
            set {
                if ((this.NetQtyField.Equals(value) != true)) {
                    this.NetQtyField = value;
                    this.RaisePropertyChanged("NetQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OrderedQty {
            get {
                return this.OrderedQtyField;
            }
            set {
                if ((this.OrderedQtyField.Equals(value) != true)) {
                    this.OrderedQtyField = value;
                    this.RaisePropertyChanged("OrderedQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdCode {
            get {
                return this.ProdCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdCodeField, value) != true)) {
                    this.ProdCodeField = value;
                    this.RaisePropertyChanged("ProdCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SystrxLine {
            get {
                return this.SystrxLineField;
            }
            set {
                if ((this.SystrxLineField.Equals(value) != true)) {
                    this.SystrxLineField = value;
                    this.RaisePropertyChanged("SystrxLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SystrxNo {
            get {
                return this.SystrxNoField;
            }
            set {
                if ((this.SystrxNoField.Equals(value) != true)) {
                    this.SystrxNoField = value;
                    this.RaisePropertyChanged("SystrxNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Customer.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateLoad", ReplyAction="http://tempuri.org/ICustomerService/UpdateLoadResponse")]
        void UpdateLoad(string companyID, string password, string loadNo, int vehicleID, int driverID, string VersionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateLoadStatus", ReplyAction="http://tempuri.org/ICustomerService/UpdateLoadStatusResponse")]
        void UpdateLoadStatus(string companyID, string password, string loadNo, string loadStatus, string VersionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateOrderStatus", ReplyAction="http://tempuri.org/ICustomerService/UpdateOrderStatusResponse")]
        void UpdateOrderStatus(string companyID, string password, decimal SysTrxNo, string orderStatus, string VersionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateShipment", ReplyAction="http://tempuri.org/ICustomerService/UpdateShipmentResponse")]
        DeliveryStreamCloudWinServ.Customer.ShipmentResponse UpdateShipment(string companyID, string password, DeliveryStreamCloudWinServ.Customer.ShipmentRequest shipmentReq, string VersionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateDeliveryDetails", ReplyAction="http://tempuri.org/ICustomerService/UpdateDeliveryDetailsResponse")]
        bool UpdateDeliveryDetails(string companyID, string password, DeliveryStreamCloudWinServ.Customer.DeliveryRequest deliveryReq, string VersionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/InsertTWBOLS", ReplyAction="http://tempuri.org/ICustomerService/InsertTWBOLSResponse")]
        void InsertTWBOLS(string companyID, string password, DeliveryStreamCloudWinServ.Customer.TWBOLDetails twbolDetailsReq, DeliveryStreamCloudWinServ.Customer.TWBOLItemDetails twbolitemDetailsReq, string VersionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateWagonShipment", ReplyAction="http://tempuri.org/ICustomerService/UpdateWagonShipmentResponse")]
        string UpdateWagonShipment(string companyID, string password, DeliveryStreamCloudWinServ.Customer.TWBOLDetails shipmentReq, string VersionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/EODInventoryProcess", ReplyAction="http://tempuri.org/ICustomerService/EODInventoryProcessResponse")]
        bool EODInventoryProcess(
                    int inClientID, 
                    string password, 
                    string inToSite, 
                    string inSupplierCode, 
                    string inSupplyPtCode, 
                    string inProductCode, 
                    decimal inOrgQty, 
                    decimal inAvailableQty, 
                    decimal inNetQty, 
                    int inOrderSysTrxNo, 
                    int inOrderSysTrxLineNo, 
                    int invehicleID, 
                    int inDriverID, 
                    string inUserID, 
                    string inBOLNo, 
                    System.DateTime inBOLDtTm, 
                    string inBOLSessionID, 
                    string inOverShort, 
                    string VersionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateFreightBreakdown", ReplyAction="http://tempuri.org/ICustomerService/UpdateFreightBreakdownResponse")]
        void UpdateFreightBreakdown(
                    string companyID, 
                    string password, 
                    int SysTrxNo, 
                    int FrtBrkdownline, 
                    char LegType, 
                    string OriginCity, 
                    string DestinationCity, 
                    string OriginState, 
                    string DestinationState, 
                    decimal CalcMiles, 
                    decimal ActualMiles, 
                    decimal OriginLat, 
                    decimal OriginLong, 
                    decimal DestLat, 
                    decimal DestLong, 
                    string VersionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateBOLImage", ReplyAction="http://tempuri.org/ICustomerService/UpdateBOLImageResponse")]
        void UpdateBOLImage(string companyID, string password, byte[] bolimage, byte[] BOLImagePdf, int SystrxNo, string Bolno, string VersionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateOrderPONo", ReplyAction="http://tempuri.org/ICustomerService/UpdateOrderPONoResponse")]
        void UpdateOrderPONo(string companyID, string password, string OrderNo, int SystrxNo, string PONo, string VersionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UndoShipDoc", ReplyAction="http://tempuri.org/ICustomerService/UndoShipDocResponse")]
        void UndoShipDoc(string companyID, string password, int SystrxNo, char inStatus, string VersionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateRejectedLoads", ReplyAction="http://tempuri.org/ICustomerService/UpdateRejectedLoadsResponse")]
        void UpdateRejectedLoads(string loadNumber, string rejectedNote, string customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateDeliveryNotes", ReplyAction="http://tempuri.org/ICustomerService/UpdateDeliveryNotesResponse")]
        void UpdateDeliveryNotes(string sysTrsNo, string deliveryNotes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/UpdateBOLWaitTimeDetails", ReplyAction="http://tempuri.org/ICustomerService/UpdateBOLWaitTimeDetailsResponse")]
        void UpdateBOLWaitTimeDetails(string companyID, string password, string ClientID, decimal SysTrxNo, string BOLNo, System.DateTime BOLWaitTimeStart, System.DateTime BOLWaitTimeEnd, string BOLWaitTimeComment, string VersionNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : DeliveryStreamCloudWinServ.Customer.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<DeliveryStreamCloudWinServ.Customer.ICustomerService>, DeliveryStreamCloudWinServ.Customer.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpdateLoad(string companyID, string password, string loadNo, int vehicleID, int driverID, string VersionNo) {
            base.Channel.UpdateLoad(companyID, password, loadNo, vehicleID, driverID, VersionNo);
        }
        
        public void UpdateLoadStatus(string companyID, string password, string loadNo, string loadStatus, string VersionNo) {
            base.Channel.UpdateLoadStatus(companyID, password, loadNo, loadStatus, VersionNo);
        }
        
        public void UpdateOrderStatus(string companyID, string password, decimal SysTrxNo, string orderStatus, string VersionNo) {
            base.Channel.UpdateOrderStatus(companyID, password, SysTrxNo, orderStatus, VersionNo);
        }
        
        public DeliveryStreamCloudWinServ.Customer.ShipmentResponse UpdateShipment(string companyID, string password, DeliveryStreamCloudWinServ.Customer.ShipmentRequest shipmentReq, string VersionNo) {
            return base.Channel.UpdateShipment(companyID, password, shipmentReq, VersionNo);
        }
        
        public bool UpdateDeliveryDetails(string companyID, string password, DeliveryStreamCloudWinServ.Customer.DeliveryRequest deliveryReq, string VersionNo) {
            return base.Channel.UpdateDeliveryDetails(companyID, password, deliveryReq, VersionNo);
        }
        
        public void InsertTWBOLS(string companyID, string password, DeliveryStreamCloudWinServ.Customer.TWBOLDetails twbolDetailsReq, DeliveryStreamCloudWinServ.Customer.TWBOLItemDetails twbolitemDetailsReq, string VersionNo) {
            base.Channel.InsertTWBOLS(companyID, password, twbolDetailsReq, twbolitemDetailsReq, VersionNo);
        }
        
        public string UpdateWagonShipment(string companyID, string password, DeliveryStreamCloudWinServ.Customer.TWBOLDetails shipmentReq, string VersionNo) {
            return base.Channel.UpdateWagonShipment(companyID, password, shipmentReq, VersionNo);
        }
        
        public bool EODInventoryProcess(
                    int inClientID, 
                    string password, 
                    string inToSite, 
                    string inSupplierCode, 
                    string inSupplyPtCode, 
                    string inProductCode, 
                    decimal inOrgQty, 
                    decimal inAvailableQty, 
                    decimal inNetQty, 
                    int inOrderSysTrxNo, 
                    int inOrderSysTrxLineNo, 
                    int invehicleID, 
                    int inDriverID, 
                    string inUserID, 
                    string inBOLNo, 
                    System.DateTime inBOLDtTm, 
                    string inBOLSessionID, 
                    string inOverShort, 
                    string VersionNo) {
            return base.Channel.EODInventoryProcess(inClientID, password, inToSite, inSupplierCode, inSupplyPtCode, inProductCode, inOrgQty, inAvailableQty, inNetQty, inOrderSysTrxNo, inOrderSysTrxLineNo, invehicleID, inDriverID, inUserID, inBOLNo, inBOLDtTm, inBOLSessionID, inOverShort, VersionNo);
        }
        
        public void UpdateFreightBreakdown(
                    string companyID, 
                    string password, 
                    int SysTrxNo, 
                    int FrtBrkdownline, 
                    char LegType, 
                    string OriginCity, 
                    string DestinationCity, 
                    string OriginState, 
                    string DestinationState, 
                    decimal CalcMiles, 
                    decimal ActualMiles, 
                    decimal OriginLat, 
                    decimal OriginLong, 
                    decimal DestLat, 
                    decimal DestLong, 
                    string VersionNo) {
            base.Channel.UpdateFreightBreakdown(companyID, password, SysTrxNo, FrtBrkdownline, LegType, OriginCity, DestinationCity, OriginState, DestinationState, CalcMiles, ActualMiles, OriginLat, OriginLong, DestLat, DestLong, VersionNo);
        }
        
        public void UpdateBOLImage(string companyID, string password, byte[] bolimage, byte[] BOLImagePdf, int SystrxNo, string Bolno, string VersionNo) {
            base.Channel.UpdateBOLImage(companyID, password, bolimage, BOLImagePdf, SystrxNo, Bolno, VersionNo);
        }
        
        public void UpdateOrderPONo(string companyID, string password, string OrderNo, int SystrxNo, string PONo, string VersionNo) {
            base.Channel.UpdateOrderPONo(companyID, password, OrderNo, SystrxNo, PONo, VersionNo);
        }
        
        public void UndoShipDoc(string companyID, string password, int SystrxNo, char inStatus, string VersionNo) {
            base.Channel.UndoShipDoc(companyID, password, SystrxNo, inStatus, VersionNo);
        }
        
        public void UpdateRejectedLoads(string loadNumber, string rejectedNote, string customerId) {
            base.Channel.UpdateRejectedLoads(loadNumber, rejectedNote, customerId);
        }
        
        public void UpdateDeliveryNotes(string sysTrsNo, string deliveryNotes) {
            base.Channel.UpdateDeliveryNotes(sysTrsNo, deliveryNotes);
        }
        
        public void UpdateBOLWaitTimeDetails(string companyID, string password, string ClientID, decimal SysTrxNo, string BOLNo, System.DateTime BOLWaitTimeStart, System.DateTime BOLWaitTimeEnd, string BOLWaitTimeComment, string VersionNo) {
            base.Channel.UpdateBOLWaitTimeDetails(companyID, password, ClientID, SysTrxNo, BOLNo, BOLWaitTimeStart, BOLWaitTimeEnd, BOLWaitTimeComment, VersionNo);
        }
    }
}
